### ISSUE TITLE
Error opening PNG file in 1.0.31

### ISSUE THREAD

**Issue by cassidyjames** [hezral/inspektor#28]
Tried opening a PNG file, and got this in Terminal:

```
Traceback (most recent call last):
  File "/usr/share/com.github.hezral.inspektor/application.py", line 79, in do_activate
    self.window.load_metadata(self.file, metadata)
  File "/usr/share/com.github.hezral.inspektor/window.py", line 262, in load_metadata
    self.get_comments = self.parser.get_file_comments(self.file.get_path())
  File "/usr/share/com.github.hezral.inspektor/parser.py", line 66, in get_file_comments
    run_executable = subprocess.Popen([self.getfattr, '-n', 'user.comment', '--only-values', '--absolute-names', file], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1278, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by hezral** [comment]
I'm not able to reproduce this. Tried running in Terminal and it worked. May i know how you ran it specifically?
Not in the gif but also tested run with just the filename 

![error](https://user-images.githubusercontent.com/762735/95271792-59737e80-0871-11eb-9933-d72c714fc5f1.gif)

**Comment by cassidyjames** [comment]
I just ran Inspektor and chose a screenshot, then it closed. I then ran it from Terminal and chose the same screenshot, getting the error above. I can see if I can reproduce it and provide the PNG file as well.

**Comment by hezral** [comment]
I'm trying to setup a fresh Hera install to test as well. 
Is it possible to share the PNG file and also the deb file?

Hmm..the error shows that the file path is missing, but from what you say, the dialog opened and went till selection of a file.
I've not changed any part of that code since trying to submit to AppCenter. Will test it on fresh Hera install.

**Comment by hezral** [comment]
Able to reproduce it now on a fresh Hera install. Will take a look at it :)

**Comment by hezral** [comment]
Found the issue, it was missing the **attr** package in the debian/control file. 
Sorry, I assumed it was part of the default install.
