### ISSUE TITLE
Change required for AppCenter: App must provide own GUI before a system dialog

### ISSUE THREAD

**Issue by cassidyjames** [hezral/inspektor#29]
Thanks for submitting your app to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Your app should provide its own GUI before showing a system dialog, i.e. a File Open dialog. Currently, there is no information about what file the user is picking—or any other instructions in the app—which can lead to confusion. We have amended the publishing requirements to clarify this: https://docs.elementary.io/develop/appcenter/publishing-requirements#launching

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). As always, if you have any questions you can reply here.

**Comment by hezral** [comment]
Got it, thanks. I've made the changes https://github.com/hezral/inspektor/commit/d98c7886d63636435442d63195473eef58065a26 so that it displays the main window first, then open the file open dialog.

**Comment by cassidyjames** [comment]
Ah, I guess I should have clarified: your app should show a UI first, and **require user action** to open the system dialog. I think I can approve your initial release as-is, but we'll be clarifying that tin the publishing requirements and may enforce it in the future.

**Comment by hezral** [comment]
oh ok. hmm I'll think about how to do that. Technically it does show the UI first but its a split second gap since it requires an input to function. I suppose i can display a dialog message then a button to open a file.
