### ISSUE TITLE
Package as Flatpak for elementary OS 6

### ISSUE THREAD

**Issue by danirabbit** [hezral/inspektor#34]
As you might have heard, AppCenter is going Flatpak! For elementary OS 6, we will not longer be accepting Debian packaging, so your app will need to be updated.

We have documentation on our developer guide for writing your Flatpak manifest here: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging#flatpak-manifest

Also, in case you missed it, elementary OS 6 beta 2 is [now available](https://builds.elementary.io). This is a great time to get your app packaged up as Flatpak and test that everything is working before the final release. AppCenter submission for OS 6 will be open soon, so don't delay :)

**Comment by cshaa** [comment]
I really miss Inspektor on Odin, it's been a great app :'((

**Comment by hezral** [comment]
i've been updating my other apps. will look at this and have it available soon. 
There is a needed update to the app as well before i can submit it. 

thanks for the interest! if you have any suggestions, please open a new issue

**Comment by hezral** [comment]
Closed, pending AppCenter review
