### ISSUE TITLE
Flatpak permissions seem too broad

### ISSUE THREAD

**Issue by danirabbit** [hezral/inspektor#37]
Hey there,

While reviewing your app I noticed it has quite a lot of permissions here that don't seem necessary:
```
  - --share=network
  - --socket=pulseaudio
  # talk to dbus session
  - --socket=session-bus
  # needed for perfers-color-scheme
  - --system-talk-name=org.freedesktop.Accounts
  # access home diectory
  - --filesystem=home
```

I'm wondering if you can clarify these permissions. It seems like your app should be able to work with the file chooser portal and I don't see any features that would require network, pulseaudio, or session access. You can also drop accounts since there is a settings portal for dark style now

**Comment by hezral** [comment]
Fixed with https://github.com/hezral/inspektor/commit/e529be85b772736ebe57be926d953f154a08202b and https://github.com/hezral/inspektor/commit/8b5a1b5550fa06b9c8269f4ec24cce5b117cbe4f

Pulseaudio is for playing audio files preview, i think this is allowed?

Rest has been removed.

**Comment by danirabbit** [comment]
Reopening since this still seems to contain the home permission that shouldn't be needed here

**Comment by hanaral** [comment]
I believe home permissions may be needed for drag and drop (Firefox flatpak certainly does)

**Comment by danirabbit** [comment]
Ah yeah after looking at the flatpak repo it seems the file transfer portal is implemented for GTK4 but not for GTK3, so home permission is needed for now
