### ISSUE TITLE
Can't read app name from flatpak bundle

### ISSUE THREAD

**Issue by danirabbit** [hezral/inspektor#39]
This app seems to have the same problem a couple of your other recent submissions have. The bundle can't be installed with Sideload since it never returns a valid app name.

If we install manually with Terminal and go to System Settings → Applications → Permissions you can see it falls back to app ID as app name can't be read from appdata

**Comment by hezral** [comment]
Found the culprit, somehow i had this `appstream-compose: false` in the manifest, removed and it properly shows the app name now in System Settings. 

Fixed with https://github.com/hezral/inspektor/commit/e529be85b772736ebe57be926d953f154a08202b
