### ISSUE TITLE
Don’t bundle codecs

### ISSUE THREAD

**Issue by danirabbit** [hezral/inspektor#40]
For licensing reasons we can’t redistribute FFMpeg/LibAV on AppCenter

it’s not really advised to bundle the gstreamer codecs either. Those should be available from the host system. Is there a specific reason you chose to try bundling codecs?

**Comment by hezral** [comment]
hmm.. ok. i'm using it for generating previews for audio and video files. 
As you mentioned, since the codes are not bundled, by default video can't play either, for example x264 videos show up blank in Videos as well. 

I'll have to change the preview mechanism and reduce its functions since i can't bundle it.

**Comment by hezral** [comment]
related topic, i'm making an app that uses the flatpak-spawn to access host system command and filesystem. Of course in a genuine/good way and will be documented in the manifest and source code. 
I see Flathub allows that but what is AppCenter's policy on that? 

Examples:
Accessing /proc directory to read process stat files to get its cpu usage
Suspend or resume a process

These are like a system monitor app which within the sandbox is not possible

**Comment by danirabbit** [comment]
@hezral since there's not a proper process monitor API yet, that seems reasonable

As for the codecs, I think we want to keep that as something from the platform since this is a security concern

**Comment by hezral** [comment]
I understand, i've dropped the requirements for now with https://github.com/hezral/inspektor/commit/6c8d87a5c3fccb3f5fa104b1f8ea0f89192a082d, will do a new release. 

as for the flatpak-spawn question, good to know 😄
