### ISSUE TITLE
Inaccurate OARS data?

### ISSUE THREAD

**Issue by danirabbit** [hezral/inspektor#41]
Your app seems to have `<content_attribute id="social-info">mild</content_attribute>` but it doesn't have network access. Possible copy/paste error?

Also, be aware that in general you don't have to add tags for values of `none`. So your oars tags can look like:

```
  <content_rating type="oars-1.1">
    <content_attribute id="social-info">mild</content_attribute>
  </content_rating>
```

or if this tag is not valid:

```
  <content_rating type="oars-1.1" />
```

**Comment by hezral** [comment]
Fixed with https://github.com/hezral/inspektor/commit/19561e99a7435146ab8adb5ab7681ddd7d4f5db4 i didn't know it can be totally empty 😅
