### ISSUE TITLE
Dargging a second file when info is shown for first file does nothing.

### ISSUE THREAD

**Issue by rohmishra** [hezral/inspektor#43]
Currently, if you launch the app from launcher, drag a file to it and are viewing information about file1, dragging file2 has no effect.

Expected result:
The app should either: 
a. show information for file2, closing file1 properties _or_ 
b. show file2 properties in a new tab _or_ 
c. if this is supposed to be a unsupported behaviour, have an animation rejecting the file.

Observed result:
no change.

**Comment by hezral** [comment]
thanks for reporting this. found the issue and fixed. will be releasing a new update.

**Comment by hezral** [comment]
new version released, you should get the update on AppCenter

**Comment by rohmishra** [comment]
Just tried it and it indeed works now! Thanks!
